# Generated by Django 5.0 on 2024-02-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_products_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
